version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=task_manager_dev
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=1h
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret_here
      - REFRESH_TOKEN_EXPIRES_IN=7d
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
